short_names_dict = {
    'KS Williamson (NZ)': 'Williamson',
    'SPD Smith (AUS)': 'Smith',
    'AB de Villiers (SA)': 'ABD',
    'JE Root (ENG)': 'Root',
    'V Kohli (IND)': 'Kohli',
    'Babar Azam (PAK)': 'Babar',
    'AD Mathews (SL)': 'Mathews',
    'LRPL Taylor (NZ)': 'Taylor',
    'DA Warner (AUS)': 'Warner',
    'RG Sharma (IND)': 'Sharma',
    'LD Chandimal (SL)': 'Chandimal',
    'Mushfiqur Rahim (BAN)': 'Mushfiqur',
    'Sarfaraz Ahmed (PAK)': 'Sarfaraz',
    'Shakib Al Hasan (BAN)': 'Shakib',
    'Mohammad Hafeez (PAK)': 'Hafeez',
    'Q de Kock (SA)': 'de Kock',
    'DM de Silva (SL)': 'de Silva',
    'S Dhawan (IND)': 'Dhawan',
    'BKG Mendis (SL)': 'Mendis',
    'JM Bairstow (ENG)': 'Bairstow',
    'Mahmudullah (BAN)': 'Mahmudullah',
    'Litton Das (BAN)': 'Litton',
    'AK Markram (SA)': 'Markram',
    'T Bavuma (SA)': 'Bavuma',
    'KL Rahul (IND)': 'Rahul',
    'JC Buttler (ENG)': 'Buttler',
    'MM Ali (ENG)': 'Ali'
}
